BUILD_DOCS=yes
BUILD_DOCS_PDF=no
BUILD_DOCS_HTML=yes


DOC_SRCDIR:=$(shell pwd)
DOC_DIR:=$(DOC_SRCDIR)/../

LOC_HL_DIR=$(DOC_SRCDIR)/source-highlight
LOC_LANG_MAP=$(LOC_HL_DIR)/local/lang.map

include source-highlight/Submakefile
include Submakefile
